### ISSUE TITLE
Create a Endpoint to Update the exsisting user 

### ISSUE THREAD

**Issue by saahilanande** [kamran-gafoor/Coursepedia-Backend#8]
Create a Api endpoint which would take objectid as a parameter from URL parameter and update the document fields. Its almost same as the adduser endpoint just use different function.

**Comment by kamran-gafoor** [comment]
Created the endpoint to update the existing users.

**Comment by saahilanande** [comment]
Add Validation to the request body

**Comment by kamran-gafoor** [comment]
Validated the request body
